language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: "pip install -e ."
script:
  - mboptimize check -z 8 examples/water_125_188_z8-z14.mbtiles || true
  - mbverify missing examples/water_125_188_z8-z14.mbtiles 125 188 -z 8 -Z 14
  - mbverify redundant examples/water_125_188_z8-z14.mbtiles 125 188 -z 8 -Z 14
  - mboptimize check -z 8 examples/optimized_water_125_188_z8.mbtiles
  - mboptimize remove -z 8 examples/water_125_188_z8-z14.mbtiles > /dev/null
  - mbverify missing examples/water_125_188_z8-z14.mbtiles 125 188 -z 8 -Z 14 > /dev/null || true
  - mbverify size -s 500000 examples/water_125_188_z8-z14.mbtiles
  - mboptimize check -z 8 examples/water_125_188_z8-z14.mbtiles
